### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by konart** [filter1/Sublime-Text-Plugins-for-Frontend-Web-Development#1]
I think it should be mentioned that ST3 also features a menu entry to install Package Control since build 3124

**Comment by cstuncsik** [comment]
Also a really good one if you don't want to reinstall all your packages manually after a fresh install of ST is [Sync Settings](https://packagecontrol.io/packages/Sync%20Settings)

**Comment by jfilter** [comment]
Thanks guys. I added both.
