### ISSUE TITLE
5 Awesome plugins

### ISSUE THREAD

**Issue by seyedi** [filter1/Sublime-Text-Plugins-for-Frontend-Web-Development#11]
Hi, I wrote a post on [CSSTricks](https://css-tricks.com/5-awesome-sublime-plugins-wont-find-top-plugin-posts/) recently talking about 5 great plugins. I thought they could go on this list as well.

Cheers!

**Comment by jfilter** [comment]
Cheers mate. Console Wrap was already on the list and I added Text Pastry. The other three undeniable solve specific problems, but I don't want the list to grow a lot longer. It will get quite overwhelming at some point. I will think about whether I add them or not. But thanks anyway for your input!
