### ISSUE TITLE
Feature Request - Directory with /Package/User settings

### ISSUE THREAD

**Issue by eele94** [filter1/Sublime-Text-Plugins-for-Frontend-Web-Development#15]
Hello I am currently looking for a good setup, but I am to lazy to configurate all the packages you provide on your list. Wouldn't it be nice if we have a folder on this repo that we can clone and copy/sync with our own sublime text?
https://packagecontrol.io/docs/syncing

Would really be awesome if there is a global configuration repo for Sublime Text!

Thanks!

**Comment by rperrote** [comment]
Sync of package control is private. Install all plugins what you want and install Sync Settings.

Regards

**Comment by eele94** [comment]
@rperrote What are you talking about??
I don't think you understand what I mean.

I do NOT want to install all packages myself, I rather use a preconfigured repo with packages that are listed in this Readme.md

With kinds regards

**Comment by rperrote** [comment]
I understand clearly. Is more work than the owner create a git repository with ST settings more than you get off the plugins you want and use your own system synchronization. In addition, public settings are dangerous if you have an ST license.

I know two plugins that synchronize the configuration. With gist and dropbox. Both private.

If the owner of the repository does, it would still have the problem of having plugins separated from the global plugins.

Sorry for my English.

**Comment by jfilter** [comment]
The package settings change quite regularly and I don't want to maintain it. In addition, I encourage you to get to know the packages on your own to better understand what problems they solve.
