### ISSUE TITLE
JavaScript Enhancements plugin

### ISSUE THREAD

**Issue by pichillilorenzo** [filter1/Sublime-Text-Plugins-for-Frontend-Web-Development#16]
Hi!

I'm the author of [JavaScript Completions](https://github.com/pichillilorenzo/JavaScript-Completions). Now I released a new plugin called [JavaScript Enhancements](https://github.com/pichillilorenzo/JavaScriptEnhancements) that offers not only a smart and better javascript autocomplete but also a lot of features about creating, developing and managing javascript projects. You could use it also in existing projects. See the Wiki for more information about all the features that it offers and for the examples.

It will turn Sublime Text into a JavaScript IDE like!

OS supported now are Mac OS X and Linux.

Please take a look at it, and if you want, add it to your list! Thanks 😄

**Comment by jfilter** [comment]
Hey there, when your plugin is available on package control, I am happy to accept a PR with your plugin (and a description). 😉
