### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jorgeatgu** [filter1/Sublime-Text-Plugins-for-Frontend-Web-Development#4]
# HTML & CSS
- [eCSSTRactor](https://github.com/hudochenkov/ecsstractor) plugin for extracting class names from HTML and generate CSS stylesheet for following work
- [emmetOneLine](https://github.com/kakRostropovich/EmmetOneLine) plugin allows you to type a few css-property by a space and a time to deploy them with Emmet.
- [Goto CSS declaration](https://github.com/rmaksim/Sublime-Text-2-Goto-CSS-Declaration) Goto CSS declaration in an open *.css file

# Linter 
- [SublimeLinter-contrib-stylelint](https://github.com/kungfusheep/SublimeLinter-contrib-stylelint) plugin for SublimeLinter provides an interface to stylelint.

# Other 
- [Local History](https://github.com/vishr/local-history) plugin for maintaining local history of files.
- [Project Manager](https://github.com/randy3k/ProjectManager) Project Manager will help organizing the project files by putting them in a centralized location

**Comment by rajikaimal** [comment]
# Auto formatting tools #
- [Prettier](https://github.com/danreeves/sublime-prettier) a Sublime Text 3 plugin for Prettier.

**Comment by jfilter** [comment]
@rajikaimal: Thanks! I will add this updated plugin for Prettier: https://github.com/jonlabelle/SublimeJsPrettier

**Comment by jfilter** [comment]
@jorgeatgu: Thanks! I added the last three plugins. I am not so sure about the first three ones. I will think about it. ;)
