### ISSUE TITLE
 What's the name of the font and theme used in the gif images?

### ISSUE THREAD

**Issue by 4goodapp** [filter1/Sublime-Text-Plugins-for-Frontend-Web-Development#6]

**Comment by jfilter** [comment]
Solarized (Light): http://ethanschoonover.com/solarized
Input Font Sans: http://input.fontbureau.com

**Comment by 4goodapp** [comment]
Thanks, 
It got to be the gif quality then, I thought it has a grid texture, which I was mostly interested. 
What variant of Input is it? Am already using Input but mine is narrower.

**Comment by jfilter** [comment]
It's "Input Sans Narrow". There exists a lot of variations of the typeface.
