### ISSUE TITLE
recommend plugin: Package Syncing

### ISSUE THREAD

**Issue by vlaw** [filter1/Sublime-Text-Plugins-for-Frontend-Web-Development#8]
I think [Package Syncing]<https://packagecontrol.io/packages/Package%20Syncing> is a good plugin. As the author said:

> Keep your Sublime Text installations synchronised across multiple machines

It can sync settings with git repo, not gist.

**Comment by jfilter** [comment]
Okay, cool. Thanks, I added it. 😉
